# Use the official Python image as a base
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python script and data files
COPY model9.py .
COPY CricketStats-Dream11Hackathon.xlsx .
COPY SquadPlayerNames.xlsx .

# Set the default command to run the script
CMD ["python3", "model9.py"]

